# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool: onpremise
#  vmImage: 'ubuntu-latest'    # examples of other options: 'macOS-10.13', 'vs2017-win2016', 'ubuntu-16.04'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run compile
    tsc --target ES6 --strict true --project tsconfigs/production.json
    npm run build
  displayName: 'npm install & build'

- script: 
    npm install -g gulp
    gulp                    # include any additional options that are needed
  displayName: 'gulp start'




- task: CopyFiles@2
  inputs:
    SourceFolder: '$(System.DefaultWorkingDirectory)'
    Contents: |
      *.js
      package.json
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: $(Build.ArtifactStagingDirectory)
    artifactName: MyBuildOutputs
    publishLocation: filePath
    targetPath: $(Build.ArtifactStagingDirectory)/test/
    #parallel: false # Optional
    #parallelCount: # Optional